package constants

const (
	PROPERTY_OPERATION_ID = "operationId"
	PROPERTY_SUMMARY      = "summary"
	PROPERTY_DESCRIPTION  = "description"
	PROPERTY_TAGS         = "tags"
	PROPERTY_PARAMETERS   = "parameters"
	PROPERTY_REQUEST_BODY = "requestBody"
	PROPERTY_EXAMPLE      = "example"
)

type _OptionalProperties map[string][]string

var OptionalProperties = _OptionalProperties{
	HTTP_GET: {
		PROPERTY_OPERATION_ID,
		PROPERTY_SUMMARY,
		PROPERTY_DESCRIPTION,
		PROPERTY_TAGS,
		PROPERTY_PARAMETERS,
		PROPERTY_EXAMPLE,
	},
	HTTP_POST: {
		PROPERTY_OPERATION_ID,
		PROPERTY_SUMMARY,
		PROPERTY_DESCRIPTION,
		PROPERTY_TAGS,
		PROPERTY_PARAMETERS,
		PROPERTY_REQUEST_BODY,
		PROPERTY_EXAMPLE,
	},
	HTTP_PUT: {
		PROPERTY_OPERATION_ID,
		PROPERTY_SUMMARY,
		PROPERTY_DESCRIPTION,
		PROPERTY_TAGS,
		PROPERTY_PARAMETERS,
		PROPERTY_REQUEST_BODY,
		PROPERTY_EXAMPLE,
	},
	HTTP_DELETE: {
		PROPERTY_OPERATION_ID,
		PROPERTY_SUMMARY,
		PROPERTY_DESCRIPTION,
		PROPERTY_TAGS,
		PROPERTY_PARAMETERS,
		PROPERTY_EXAMPLE,
	},
}
