version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - gocritic
    - errorlint
    - errname
    - exportloopref
formatters:
  enable:
    - gofumpt
    - goimports
    - gci
