version: "2"
run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck
    - gocritic
    - errorlint
    - errname
    - exportloopref
    - gofumpt
    - goimports
    - gci
    - revive
    - misspell
    - gosec
    - prealloc
