name: Generate and Update Build File

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths-ignore:
      - 'update-binary-files/**'

permissions:
  contents: write
  pull-requests: write

# 同じブランチを扱うジョブは 1 本だけに
concurrency:
  group: update-binary-files
  cancel-in-progress: true

jobs:
  build:
    if: github.event.pull_request.merged == true && !startsWith(github.head_ref, 'update-binary-files')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - run: go mod tidy
      - run: go test ./...
      - run: go build -o swagen-v2

      - uses: actions/upload-artifact@v4
        with:
          name: binary
          path: swagen-v2

  create-pr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/download-artifact@v4
        with:
          name: binary
          path: .

      - name: Configure Git
        run: |
          git config --global user.name  'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Prepare update-binary-files branch
        run: |
          # 最新 main を取得してその上に作り直す
          git fetch origin main
          git checkout -B update-binary-files origin/main

          # 生成物を配置
          git add -f swagen-v2

          # 差分がなければスキップ
          if git diff --cached --quiet; then
            echo "No binary changes – skip push."
            exit 0
          fi

          git commit -m "chore(ci): update binary artifact"
          # lease 付き強制 push で安全に上書き
          git push --force-with-lease origin update-binary-files

      - name: Create / update PR
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(ci): update binary artifact"
          title: "Update binary artifact"
          branch: "update-binary-files"
          base: "main"
          delete-branch: true
