name: Check golangci lint

on: 
  pull_request:

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.59.2

      - name: Run golangci-lint
        run: |
          golangci-lint run ./......
          # If you want to see the output even if there are no issues, uncomment the following line
          # golangci-lint run ./... --print-issued-lines=false
        # Continue even if golangci-lint finds issues, to allow the workflow to complete
        continue-on-error: true