name: Release by goreleaser

on:
  pull_request:
    types: [closed]
    branches: [main]
    paths-ignore:
      - 'update-binary-files/**'

permissions:
  contents: write
  pull-requests: write

# 同じブランチを扱うジョブは 1 本だけに
concurrency:
  group: update-binary-files
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # コミットログからリリースノートを作るならこのオプションが必要
          fetch-depth: 0

      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}